name: Build & Publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - run: npm ci

      - uses: microsoft/playwright-github-action@v1
      - name: Run your tests
        run: npm start

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

      - uses: actions/upload-artifact@v2
        with:
          name: vuetify-session-events.ldjson
          path: vuetify-session-events.ldjson
